#!/bin/sh
# setup_pf_gpu_node.sh — Install minimal pf firewall for a Zed GPU node
#
# Creates /etc/pf.conf with:
#   - NAT for Bastille jails (if bastille0 exists)
#   - Open EPMD (4369) + BEAM distribution ports (9100-9200) from LAN
#   - Pass all on loopback
#   - Default pass (permissive — tighten later)
#
# Run with doas:
#   doas sh setup_pf_gpu_node.sh
#
# Idempotent — backs up existing pf.conf before overwriting.

set -e

# Detect external interface
EXT_IF=$(ifconfig | grep -B1 "inet " | grep -v lo0 | grep -v 127.0.0.1 | grep "UP" | head -1 | cut -d: -f1)
if [ -z "$EXT_IF" ]; then
    EXT_IF=$(route -n get default 2>/dev/null | grep interface | awk '{print $2}')
fi
if [ -z "$EXT_IF" ]; then
    echo "[error] Cannot detect external interface. Set EXT_IF manually."
    exit 1
fi

echo "Detected interface: $EXT_IF"

# Backup existing pf.conf
if [ -f /etc/pf.conf ]; then
    cp /etc/pf.conf "/etc/pf.conf.bak.$(date +%Y%m%d%H%M%S)"
    echo "Backed up existing /etc/pf.conf"
fi

# Write pf.conf
cat > /etc/pf.conf << PFEOF
# /etc/pf.conf — Zed GPU node (generated by setup_pf_gpu_node.sh)
#
# Permissive ruleset for a LAN-attached GPU compute node.
# Erlang distribution: EPMD 4369 + BEAM ports 9100-9200.

ext_if = "$EXT_IF"

# Loopback — never filter
set skip on lo0

# Bastille NAT (if jails exist)
nat on \$ext_if from (bastille0:network) to any -> (\$ext_if) 2>/dev/null || true
rdr-anchor "rdr/*"

# Erlang distribution — open from LAN
pass in on \$ext_if proto tcp from 192.168.0.0/24 to any port 4369
pass in on \$ext_if proto tcp from 192.168.0.0/24 to any port 9100:9200

# SSH
pass in on \$ext_if proto tcp from any to any port 22

# Default pass (permissive LAN node)
pass
PFEOF

echo "Wrote /etc/pf.conf"

# Enable pf in rc.conf if not already
if ! sysrc -n pf_enable 2>/dev/null | grep -q YES; then
    sysrc pf_enable=YES
    echo "Enabled pf in rc.conf"
else
    echo "pf already enabled in rc.conf"
fi

# Load/reload pf
if pfctl -s info 2>/dev/null | head -1 | grep -q "Enabled"; then
    pfctl -f /etc/pf.conf
    echo "Reloaded pf rules"
else
    service pf start 2>/dev/null || pfctl -e -f /etc/pf.conf
    echo "Started pf"
fi

echo ""
echo "=== PF configured ==="
echo ""
echo "Active rules:"
pfctl -sr 2>/dev/null | head -10
echo ""
echo "Start BEAM nodes with pinned port range:"
echo "  iex --erl \"-kernel inet_dist_listen_min 9100 inet_dist_listen_max 9200\" \\"
echo "      --name gpu2@\$(ifconfig $EXT_IF | grep 'inet ' | awk '{print \$2}') \\"
echo "      --cookie zed_gpu_demo -S mix"
echo ""
